### ISSUE TITLE
Unrepeatable [MKNodeView nodeChanged:] notification crash on [MKBuy visibleStages]

### ISSUE THREAD

**Issue by awt** [Voluntarynet/Bitmarkets#15]
Process:         Bitmarkets [43138]
Path:            /Applications/Bitmarkets.app/Contents/MacOS/Bitmarkets
Identifier:      net.voluntary.Bitmarkets
Version:         0.8.7.12 (0.8.7.12)
Code Type:       X86-64 (Native)
Parent Process:  launchd [145]
Responsible:     Bitmarkets [43138]
User ID:         501

Date/Time:       2014-11-24 07:36:40.242 -0800
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  714BC9EB-E3C8-D3F2-6189-FFD545CEB3F3

Sleep/Wake UUID: EAA99994-249D-4C9F-B706-0E128B28F88F

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000018

VM Regions Near 0x18:
--> 
    __TEXT                 000000010c024000-000000010c06c000 [  288K] r-x/rwx SM=COW  /Applications/Bitmarkets.app/Contents/MacOS/Bitmarkets

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff8a24679f objc_retain + 15
1   net.voluntary.Bitmarkets      	0x000000010c025def -[MKBuy visibleStages] + 143
2   net.voluntary.Bitmarkets      	0x000000010c05208b -[MKStepsView layout] + 91
3   net.voluntary.Bitmarkets      	0x000000010c029989 -[MKTxProgressView layout] + 169
4   net.voluntary.Bitmarkets      	0x000000010c02a3ab -[MKTxProgressView syncFromNode] + 1499
5   net.voluntary.Bitmarkets      	0x000000010c05290b -[MKNodeView nodeChanged:] + 91
6   com.apple.CoreFoundation      	0x00007fff907e6e0c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
7   com.apple.CoreFoundation      	0x00007fff906da82d _CFXNotificationPost + 2893
8   com.apple.Foundation          	0x00007fff89ac6e4a -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
9   net.voluntary.NavNodeKit      	0x000000010c1261ea -[NavNode justPostSelfChanged] + 106
10  com.apple.Foundation          	0x00007fff89b28347 __NSFireDelayedPerform + 333
11  com.apple.CoreFoundation      	0x00007fff9077f3e4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
12  com.apple.CoreFoundation      	0x00007fff9077ef1f __CFRunLoopDoTimer + 1151
13  com.apple.CoreFoundation      	0x00007fff907f05aa __CFRunLoopDoTimers + 298
14  com.apple.CoreFoundation      	0x00007fff9073a6a5 __CFRunLoopRun + 1525
15  com.apple.CoreFoundation      	0x00007fff90739e75 CFRunLoopRunSpecific + 309
16  com.apple.HIToolbox           	0x00007fff87683a0d RunCurrentEventLoopInMode + 226
17  com.apple.HIToolbox           	0x00007fff876837b7 ReceiveNextEventCommon + 479
18  com.apple.HIToolbox           	0x00007fff876835bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
19  com.apple.AppKit              	0x00007fff867c824e _DPSNextEvent + 1434
20  com.apple.AppKit              	0x00007fff867c789b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
21  com.apple.AppKit              	0x00007fff867bb99c -[NSApplication run] + 553
22  com.apple.AppKit              	0x00007fff867a6783 NSApplicationMain + 940
23  net.voluntary.Bitmarkets      	0x000000010c02a6f2 main + 34
24  libdyld.dylib                 	0x00007fff8f4035fd start + 1

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff8f41c662 kevent64 + 10
1   libdispatch.dylib             	0x00007fff9050f421 _dispatch_mgr_invoke + 239
2   libdispatch.dylib             	0x00007fff9050f136 _dispatch_mgr_thread + 52

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff8f417a1a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff8f416d18 mach_msg + 64
2   com.apple.CoreFoundation      	0x00007fff9073af15 __CFRunLoopServiceMachPort + 181
3   com.apple.CoreFoundation      	0x00007fff9073a539 __CFRunLoopRun + 1161
4   com.apple.CoreFoundation      	0x00007fff90739e75 CFRunLoopRunSpecific + 309
5   com.apple.AppKit              	0x00007fff8696805e _NSEventThread + 144
6   libsystem_pthread.dylib       	0x00007fff8e91a899 _pthread_body + 138
7   libsystem_pthread.dylib       	0x00007fff8e91a72a _pthread_start + 137
8   libsystem_pthread.dylib       	0x00007fff8e91efc9 thread_start + 13

Thread 3:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	0x00007fff8f417a1a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff8f416d18 mach_msg + 64
2   com.apple.CoreFoundation      	0x00007fff9073af15 __CFRunLoopServiceMachPort + 181
3   com.apple.CoreFoundation      	0x00007fff9073a539 __CFRunLoopRun + 1161
4   com.apple.CoreFoundation      	0x00007fff90739e75 CFRunLoopRunSpecific + 309
5   com.apple.Foundation          	0x00007fff89b2aff7 +[NSURLConnection(Loader) _resourceLoadLoop:] + 348
6   com.apple.Foundation          	0x00007fff89b2adfb __NSThread__main__ + 1318
7   libsystem_pthread.dylib       	0x00007fff8e91a899 _pthread_body + 138
8   libsystem_pthread.dylib       	0x00007fff8e91a72a _pthread_start + 137
9   libsystem_pthread.dylib       	0x00007fff8e91efc9 thread_start + 13

Thread 4:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff8f41b9aa __select + 10
1   com.apple.CoreFoundation      	0x00007fff90786a03 __CFSocketManager + 867
2   libsystem_pthread.dylib       	0x00007fff8e91a899 _pthread_body + 138
3   libsystem_pthread.dylib       	0x00007fff8e91a72a _pthread_start + 137
4   libsystem_pthread.dylib       	0x00007fff8e91efc9 thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff8f41be6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8e91bf08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8e91efb9 start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff8f41be6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8e91bf08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8e91efb9 start_wqthread + 13

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff8f41be6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8e91bf08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8e91efb9 start_wqthread + 13

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff8f41be6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8e91bf08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8e91efb9 start_wqthread + 13

Thread 9:
0   libsystem_kernel.dylib        	0x00007fff8f41be6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff8e91bf08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff8e91efb9 start_wqthread + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00000000003f708d  rcx: 0x0000000000000007  rdx: 0x0000000000000001
  rdi: 0x0000000000000018  rsi: 0x000060800004fc30  rbp: 0x00007fff53bd8c30  rsp: 0x00007fff53bd8bd8
   r8: 0x0000000000003fff   r9: 0xffff9fffffe0d3ff  r10: 0x000000011129b560  r11: 0x000000010c07c438
  r12: 0x00000000003f708d  r13: 0x00007fff53bd9150  r14: 0x0000618001e45550  r15: 0x00007fff53bd90c0
  rip: 0x00007fff8a24679f  rfl: 0x0000000000010246  cr2: 0x0000000000000018
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14

**Comment by stevedekorte** [comment]
I think some of the recent updates to how notifications were done may have fixed this, so I'm closing until we observe it again.
