### ISSUE TITLE
Ready for use?

### ISSUE THREAD

**Issue by eragmus** [Voluntarynet/Bitmarkets#29]
Hi, to speak vaguely and generally, currently on reddit DNM, there seems to be an issue with a large market going offline while it fixes a Tor issue. That market may be benevolent, but there is still lots of trust required and incentive to exit scam.

Is Bitmarkets ready to begin filling the void for the Mac users of DNM at least, while Linux and Windows users wait until later this year to use it (ETA for the port btw?)? The promo video implies it can, but can Bitmarkets really replace these centralized markets, in terms of duplicating the UI/UX of those options to provide users a seamless transition?

People there are currently discussing 'what to trust?' since that large trusted market is offline for now.

Thanks.

**Comment by stevedekorte** [comment]
Hi eragmus, Bitmarkets is working and ready for use (on OSX atm). It's trust model is unlike the centralized services as there is no service or escrow agents you need to trust (thanks to our use of bitmessage for sharing the order book and mutual deposit two party escrow). And communications with the Bitcoin and Bitmessage networks is done via Tor (which is easy to verify with the Little Snitch app). You do need to trust that we as developers (and the bitcoinj developers) haven't put in some way to steal wallet funds, but all the source is open and attached to our real identities and a user can minimize exposure by only keeping in their wallet the amounts they need to make their current purchase or sale (which we recommend anyways). Hope that helps. I'd be glad to answer any questions.

**Comment by eragmus** [comment]
Hi Steve, sounds good. So I tried the latest version and repeatedly get an error during startup: "nsrange", after which the app quits. A popup to install java also appears, even though I already have java installed. Any ideas? I tried restarting the computer too, but this didn't help.

**Comment by stevedekorte** [comment]
Which version of OSX? Can you send me the backtrace from the console.app? You may need to install the Java from the Apple link.

**Comment by eragmus** [comment]
Version 10.10.5 of OS X.

By backtrace, do you mean the following?

------

8/28/15 2:25:01.800 AM Bitmarkets[681]: killed old process 'tor' with pid: 669
8/28/15 2:25:02.806 AM Bitmarkets[681]: killed old process 'python.exe' with pid: 670
8/28/15 2:25:04.057 AM SIMBL Enabler for Sandboxed Apps[676]: Will terminate until reinvoked again by launchd.
8/28/15 2:25:08.201 AM com.apple.xpc.launchd[1]: (com.apple.imfoundation.IMRemoteURLConnectionAgent) The _DirtyJetsamMemoryLimit key is not available on this platform.
8/28/15 2:25:10.054 AM Bitmarkets[681]: refresh exception:
 exception:
name: 'NSRangeException'
reason: '*** -[NSConcreteMutableData getBytes:range:]: range {18446744073709551615, 1} causes integer overflow'
stack: '(
	0   CoreFoundation                      0x00007fff9491d03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9185476e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9491ceed +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff93c9e1a6 -[NSData(NSData) getBytes:range:] + 179
	4   BitnashKit                          0x000000010d04c1b8 -[BNServer sendMessage:withObject:withArg:] + 1512
	5   BitnashKit                          0x000000010d04bb94 -[BNServer sendMessage:withObject:] + 116
	6   BitnashKit                          0x000000010d046487 -[BNWallet status] + 71
	7   BitnashKit                          0x000000010d045c4f -[BNWallet fetch] + 703
	8   NavNodeKit                          0x000000010cff5b8d -[NavNode deepFetch] + 61
	9   NavNodeKit                          0x000000010cff5dd6 -[NavNode refresh] + 70
	10  NavNodeKit                          0x000000010cff7947 -[NavNode refreshTimerEvent] + 39
	11  Foundation                          0x00007fff93c3ca23 __NSFireTimer + 95
	12  CoreFoundation                      0x00007fff948702e4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	13  CoreFoundation                      0x00007fff9486ff73 __CFRunLoopDoTimer + 1059
	14  CoreFoundation                      0x00007fff948e353d __CFRunLoopDoTimers + 301
	15  CoreFoundation                      0x00007fff9482b608 __CFRunLoopRun + 2024
	16  CoreFoundation                      0x00007fff9482abd8 CFRunLoopRunSpecific + 296
	17  HIToolbox                           0x00007fff8c87256f RunCurrentEventLoopInMode + 235
	18  HIToolbox                           0x00007fff8c8722ea ReceiveNextEventCommon + 431
	19  HIToolbox                           0x00007fff8c87212b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	20  AppKit                              0x00007fff8d7e78ab _DPSNextEvent + 978
	21  AppKit                              0x00007fff8d7e6e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	22  AppKit                              0x00007fff8d7dcaf3 -[NSApplication run] + 594
	23  AppKit                              0x00007fff8d759244 NSApplicationMain + 1832
	24  Bitmarkets                          0x000000010cf07f32 main + 34
	25  libdyld.dylib                       0x00007fff913f15c9 start + 1
)'
8/28/15 2:25:15.050 AM com.apple.xpc.launchd[1]: (net.voluntary.Bitmarkets.229788[681]) Service exited due to signal: Broken pipe: 13

------

Does that help?

**Comment by stevedekorte** [comment]
Looks like it's having a problem talking to the BitcoinJ server, which may be because Apple's Java is not installed or isn't a compatible version. 

Can you open the Terminal.app and run the command:

/usr/bin/java -version

And let me know what it prints out?

**Comment by eragmus** [comment]
Sure, I got this from Terminal:

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by stevedekorte** [comment]
I have:

java version “1.6.0_65"

I would guess that yours should work as well. I can test that tomorrow.
In the mean time, could you try installing Apple’s latest Java that the app presents a link to?

If it turns out to be a version issue, I’ll add a version check to the app’s Java test.

**Comment by eragmus** [comment]
Okay, it looks like I've determined the problem! I use Intego VirusBarrier and always have real-time scanning enabled. I've never really had an issue before, so I didn't suspect it, but after disabling it, no more crashes occur. The wallet went from 0 to 100% and now says "0.0000 BTC".

The only issue now is that it's been maybe 30 min but it still says in the title bar "syncing with bitmessage network - 9 connections, 23 messages processed". This seems excessively, painfully slow, maybe abnormally slow. Or, is it normal?

**Comment by stevedekorte** [comment]
Good to hear you got it working. 

The perpetual Bitmessage syncing is normal (it never finishes because there are always going to be new messages on the network. Those "23 messages" are just Bitmessage network messages and may not be Bitmarkets related. The first sync takes a while but updates are quicker. 

That said, there may not be any sales posts up at the moment. It's hard to solve the chicken and egg problem of marketplaces. Other markets solve it by being the first sellers but this isn't an option available to us as we have nothing of significance to sell.

**Comment by eragmus** [comment]
Thank you for your responses. I did eventually notice 1 listing!

As to the chicken-and-egg problem, I think as long as the product is solid and offers advantages (which this product certainly does especially vis-a-vis the shady exit-scamming world of DNM), then it's just a matter of getting the word out.

As to that, I've taken the liberty to get the ball rolling here:
> https://www.reddit.com/r/DarkNetMarkets/comments/3ipub5/everyone_should_go_to_sites_that_use_multisig/cuiyrco

If you're comfortable, you could take over at this point to address questions. I don't want to accidentally say something incorrect.

On a different note, a few things...

1. I know you said the app is ready to use, but in-app there are various messages saying the app needs lots of auditing and testing before use (implying it's unsafe to use right now). Maybe those messages should be removed?

2. There was a Tor vulnerability reported recently, which caused a major DNM to go offline so that it could fix its vulnerabilities (see: https://nakedsecurity.sophos.com/2015/08/28/dark-web-market-agora-suspends-operations-due-to-tor-vulnerability/). Does this apply to BitMarkets?

3. Is Tor in BitMarkets being kept up-to-date as Tor Project releases updates?

**Comment by stevedekorte** [comment]
> On Aug 28, 2015, at 1:55 PM, eragmus <notifications@github.com> wrote:
> 
> Thank you for your responses. I did eventually notice 1 listing!
> 
> As to the chicken-and-egg problem, I think as long as the product is solid and offers advantages (which this product certainly does especially vis-a-vis the shady exit-scamming world of DNM), then it's just a matter of getting the word out.
> 
> As to that, I've taken the liberty to get the ball rolling here:
> 
> https://www.reddit.com/r/DarkNetMarkets/comments/3ipub5/everyone_should_go_to_sites_that_use_multisig/cuiyrco
> 
> If you're comfortable, you could take over at this point to address questions. I don't want to accidentally say something incorrect.

Thanks, I’ll follow it and respond to any questions.

> 
> On a different note, a few things...
> 
> 	• I know you said the app is ready to use, but in-app there are various messages saying the app needs lots of auditing and testing before use (implying it's unsafe to use right now). Maybe those messages should be removed?

Those are normal precautions for any new software. In our case, we’re dealing with software that can store and move money, so we need to be sure people use it with caution until it’s very well tested (which takes years).


> 	• There was a Tor vulnerability reported recently, which caused a major DNM to go offline so that it could fix its vulnerabilities (see: https://nakedsecurity.sophos.com/2015/08/28/dark-web-market-agora-suspends-operations-due-to-tor-vulnerability/). Does this apply to BitMarkets?

AFAICS, that’s only an issue with how Tor onion hidden services set up routing and shouldn’t be a problem for how we use Tor to talk to the Bitcoin and Bitmessage networks.

> 
> 	• Is Tor in BitMarkets being kept up-to-date as Tor Project releases updates?

Yes, we try to keep it up to date.

**Comment by eragmus** [comment]
Okay, thanks Steve.
