### ISSUE TITLE
FAQ not clearly linked on main page

### ISSUE THREAD

**Issue by eragmus** [Voluntarynet/Bitmarkets#30]
There seems to be no obvious link to https://voluntary.net/bitmarkets/faq/ on https://voluntary.net/bitmarkets/. If you scroll down on the main page, Slides / Paper / Protocol / Source / Press are visible. Logically, perhaps FAQ should also be here.

**Comment by stevedekorte** [comment]
Good idea - I've added it.

**Comment by eragmus** [comment]
Awesome :)
